reporter: "xcode"

# MARK: - General

analyzer_rules:
    - capture_variable
    - explicit_self
    - typesafe_array_init
    - unused_declaration
    - unused_import

opt_in_rules:
    - array_init
    - attributes
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - colon
    - convenience_type
    - custom_rules
    - cyclomatic_complexity
    - discouraged_object_literal
    - empty_collection_literal
    - empty_count
    - empty_string
    - enum_case_associated_values_count
    - expiring_todo
    - fatal_error_message
    - file_name
    - first_where
    - force_unwrapping
    - implicitly_unwrapped_optional
    - last_where
    - legacy_random
    - literal_expression_end_indentation
    - modifier_order
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - prefer_self_type_over_type_of_self
    - private_action
    - private_outlet
    - redundant_nil_coalescing
    - redundant_type_annotation
    - strict_fileprivate
    - todo
    - toggle_bool
    - trailing_closure
    - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_closing_braces
    - weak_delegate
    - yoda_condition
    - indentation_width

# MARK: - Native rules

attributes:
    always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

force_cast: warning
force_try: warning
legacy_hashing: error

private_over_fileprivate:
    validate_extensions: true

indentation_width:
    indentation_width: 2

nesting:
    type_level: 3

large_tuple:
    warning: 4
    error: 5

trailing_whitespace:
    ignores_empty_lines: false
    ignores_comments: false

vertical_whitespace:
    max_empty_lines: 3

function_body_length:
    warning: 150
    error: 200

type_body_length:
    warning: 300
    error: 500

identifier_name:
    min_length: 3
    severity: warning
    excluded:
        - i
        - j
        - id
        - x
        - y
        - z
        - url

type_name:
    min_length: 3
    max_length:
      warning: 50
      error: 70
    excluded:
        - ID
        - T
        - V

line_length:
    ignores_urls: true
    ignores_comments: false
    ignores_interpolated_strings: true
    warning: 160
    error: 180

file_length:
    warning: 500
    error: 1500

multiline_arguments:
    first_argument_location: next_line
    only_enforce_after_first_closure_on_first_line: true
